### ISSUE TITLE
Build fails for kernel 6.10

### ISSUE THREAD

**Issue by cl0ne** [juanro49/rtl88x2ce-dkms#16]
Greetings!

`dkms install` for kernel 6.10 fails with the following error:

```
/var/lib/dkms/rtl88x2ce/r48.488172d/build/os_dep/linux/ioctl_cfg80211.c: In function 'rtw_cfg80211_ch_switch_notify':
/var/lib/dkms/rtl88x2ce/r48.488172d/build/os_dep/linux/ioctl_cfg80211.c:443:9: error: too many arguments to function 'cfg80211_ch_switch_notify'
  443 |         cfg80211_ch_switch_notify(adapter->pnetdev, &chdef, 0, 0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/rtl88x2ce/r48.488172d/build/include/osdep_service_linux.h:93,
                 from /var/lib/dkms/rtl88x2ce/r48.488172d/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl88x2ce/r48.488172d/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl88x2ce/r48.488172d/build/os_dep/linux/ioctl_cfg80211.c:17:
./include/net/cfg80211.h:8827:6: note: declared here
 8827 | void cfg80211_ch_switch_notify(struct net_device *dev,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~
```

Could you please update this module so it can be built for kernel 6.10 as well?

**Comment by juanro49** [comment]
> Greetings!
> 
> `dkms install` for kernel 6.10 fails with the following error:
> 
> ```
> /var/lib/dkms/rtl88x2ce/r48.488172d/build/os_dep/linux/ioctl_cfg80211.c: In function 'rtw_cfg80211_ch_switch_notify':
> /var/lib/dkms/rtl88x2ce/r48.488172d/build/os_dep/linux/ioctl_cfg80211.c:443:9: error: too many arguments to function 'cfg80211_ch_switch_notify'
>   443 |         cfg80211_ch_switch_notify(adapter->pnetdev, &chdef, 0, 0);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /var/lib/dkms/rtl88x2ce/r48.488172d/build/include/osdep_service_linux.h:93,
>                  from /var/lib/dkms/rtl88x2ce/r48.488172d/build/include/osdep_service.h:50,
>                  from /var/lib/dkms/rtl88x2ce/r48.488172d/build/include/drv_types.h:27,
>                  from /var/lib/dkms/rtl88x2ce/r48.488172d/build/os_dep/linux/ioctl_cfg80211.c:17:
> ./include/net/cfg80211.h:8827:6: note: declared here
>  8827 | void cfg80211_ch_switch_notify(struct net_device *dev,
>       |      ^~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> Could you please update this module so it can be built for kernel 6.10 as well?

Can you check with latest merged PR?

**Comment by KafCoppelia** [comment]
I've tested on kernel 6.10+. #3 and #4 can be tested in depth.

**Comment by cl0ne** [comment]
@KafCoppelia @juanro49 Thanks! Successfully builds on 6.10.5
